language: scala
scala:
  - 2.11.7
before_script:
  - wget https://github.com/psforever/PSCrypto/releases/download/v1.0/pscrypto-lib-1.0.zip
  - unzip pscrypto-lib-1.0.zip
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
after_success:
    - bash <(curl -s https://codecov.io/bash)
